[package]
name = "rust_core_sensiomotor_functions_py"
version = "0.0.1"
edition = "2024"

[dependencies]
feagi_core_sensiomotor_functions = { version = "0.0.1"}
ndarray = "0.16.1"
pyo3 = { version = "0.24.1", features = ["extension-module"] }
numpy = "0.24.0"

[lib]
crate-type = ["cdylib"]