name: "Push to Bridge HUB"

on:
  push:
    branches:
      - main
    paths:
      - 'embodiments/godot-bridge/bridge_godot_python.py'
      - 'embodiments/godot-bridge/configuration.json'
  workflow_dispatch:

jobs:
  bridge_version:
    name: Bridge Update Version on Docker Hub
    runs-on: ubuntu-22.04
    if: github.repository == 'feagi/feagi-connector'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: embodiments/godot-bridge
          platforms: linux/amd64,linux/arm64
          push: true
          tags: neuraville/bridge:latest


